# Generated by Django 5.2.10 on 2026-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebank', '0003_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
