# Generated by Django 5.2.10 on 2026-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebank', '0006_cardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequest',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
