# Generated by Django 5.2.10 on 2026-02-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_facedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FaceData',
        ),
    ]
