# Generated by Django 5.2.10 on 2026-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ifsc_code',
            field=models.CharField(default='PRIME0001234', max_length=20),
        ),
    ]
